#!/usr/bin/env ruby

require 'rubygems'
require "bundler/setup"
require 'redis'
require 'em_apn_manager'

ENV["APN_KEY"]  ||= File.join(File.dirname(__FILE__),  "..", "certs", "key.pem")
ENV["APN_CERT"] ||= File.join(File.dirname(__FILE__), "..", "certs", "cert.pem")

TOKEN = "fe9515ba7556cfdcfca6530235c95dff682fac765838e749a201a7f6cf3792e6"

$redis = Redis.new

def notify
  $redis.publish "push-notification", {
    key: File.read(ENV["APN_KEY"]),
    cert: File.read(ENV["APN_CERT"]),
    token: TOKEN,
    message: "Hello User##{rand * 10000}."
  }.to_json

  EM.add_timer(get_random_time) { notify }
end

def get_random_time
  rand(5).to_f / 100.0
end

EM.run do
  notify
end
